var _ccoding_stds_main =
[
    [ "Cyclomatic Complexity", "_ccoding_stds_main.html#cstdsCyclomatic", null ],
    [ "Fan Out", "_ccoding_stds_main.html#cstdsFanOut", null ],
    [ "Recursion", "_ccoding_stds_main.html#cstdsRecursion", null ],
    [ "Gotos", "_ccoding_stds_main.html#cstdsGotos", null ],
    [ "Global Variables", "_ccoding_stds_main.html#cstdsGlobalVariables", null ],
    [ "Extern", "_ccoding_stds_main.html#cstdsExtern", null ],
    [ "Heap", "_ccoding_stds_main.html#cstdsHeap", null ],
    [ "Multiple Inclusion Guards", "_ccoding_stds_main.html#cstdsMultipleInclusionGuards", null ],
    [ "Line Length", "_ccoding_stds_main.html#cstdsLineLength", null ],
    [ "Existing Code", "_ccoding_stds_main.html#cstdsExistingCode", null ],
    [ "Naming", "_ccoding_stds_main.html#cstdsNaming", null ],
    [ "Prefixes Overview", "_ccoding_stds_main.html#cstdsPrefixesOverview", null ],
    [ "Component Interfaces", "_ccoding_stds_main.html#cstdsInterComponentInterfaces", null ],
    [ "Module Interfaces", "_ccoding_stds_main.html#cstdsInterModuleInterfaces", null ],
    [ "Files", "_ccoding_stds_main.html#cstdsFiles", null ],
    [ "Macros", "_ccoding_stds_main.html#cstdsMacros", null ],
    [ "Suffix Name", "_ccoding_stds_main.html#cstdsNameSuffix", null ],
    [ "Name Prefix", "_ccoding_stds_main.html#cstdsNamePrefix", null ],
    [ "Name Type", "_ccoding_stds_main.html#cstdsNameType", null ],
    [ "Cardinal Types", "_ccoding_stds_main.html#cstdsCardinalTypes", null ],
    [ "Enumeration Members", "_ccoding_stds_main.html#cstdsEnumerationMembers", null ],
    [ "Struct and Union Namespaces", "_ccoding_stds_main.html#cstdsStructandUnionNamespaces", null ],
    [ "Struct and Union Members", "_ccoding_stds_main.html#cstdsStructandUnionMembers", null ],
    [ "Prefix", "_ccoding_stds_main.html#cstdsPrefix", null ],
    [ "Camel Case Name", "_ccoding_stds_main.html#cstdsCamelCaseName", null ],
    [ "Verbage", "_ccoding_stds_main.html#cstdsVerbage", null ],
    [ "C Standard Abbreviations", "_c_standards_abbreviations.html", null ],
    [ "C Standard Parameters", "_c_standards_parameters.html", [
      [ "Camel Case", "_c_standards_parameters.html#cstdsparamCamelCase", null ],
      [ "Prefix", "_c_standards_parameters.html#cstdsparamPrefix", null ],
      [ "Pointers", "_c_standards_parameters.html#cstdsparamPointers", null ],
      [ "Static Variables", "_c_standards_parameters.html#cstdsparamStaticVariables", null ],
      [ "Abbreviations", "_c_standards_parameters.html#cstdsparamAbbreviations", null ],
      [ "Commenting", "_c_standards_parameters.html#cstdsparamCommenting", null ],
      [ "Separating Interface from Implementation", "_c_standards_parameters.html#cstdsparamSeparateInterfacefromImplementation", null ],
      [ "Interface Documentation", "_c_standards_parameters.html#cstdsparamInterfaceDocumentation", null ],
      [ "Function Parameters", "_c_standards_parameters.html#cstdsparamFunctionParameter", null ],
      [ "Const Pointers", "_c_standards_parameters.html#cstdsparamConstPointers", null ],
      [ "Multithreading", "_c_standards_parameters.html#cstdsparamMultithreading", null ],
      [ "Tabs", "_c_standards_parameters.html#cstdsparamTabs", null ]
    ] ]
];